---
- name: Change user passwords
  hosts: managed
  become: yes

  vars:
    users:
      - name: root
        password: "password"

  tasks:
    - name: Change password for users
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
      loop: "{{ users }}"
